
extension LocalUndocumentedStructure {
    
    /// Should be VISIBLE.
    ///
    /// Rationale:
    ///
    /// While consistency with behavior elsewhere would dictate hiding the method along with the main declaration, an exeption is necessary in this particular case as a concession to code generation tools. Users have no access to the declarations produced by autogenerated code (most notably Core Data entities), and have no way of adding documentation comments to them. Autogenerated code can be extended, and those extensions should still be documentable. The only way that is possible is by having `--skip-undocented` parse into extensions even when the main declaration has no documentation.
    ///
    /// The user should not be required to document each extension. The user may have or even need several extensions, especially when constraints or where statements are involved.
    ///
    /// Since the various documentation comments get merged using a currently undefined strategy, the user cannot write documentation that they can be sure will appear as they intend. For example, they may write documentation for one extension only to have a different blank extension squash it, or copy and paste to all extensions only to have the documentation repeated.
    ///
    /// The user should still be able to reasonably assume that if they only write documentation for one extension, that is precisely what they will get.
    ///
    /// However, when a user leaves the other extensions blank, they still likely want the methods of those other extensions to be listed. This is why extension methods should be visible even they are located in an extension that has no documentation comment of its own.
    ///
    /// Note: If a user really wants to hide an entire extension, they still have the option of explicitly opting out with `nodoc`.
    ///
    /// Methods from different extensions should be merged into a single list.
    public func should_be_VISIBLE_because_documentation_exists_for_method_and_main_structure_declaration_may_not_be_documentable() {}
    
    /// :nodoc:
    public func should_be_HIDDEN_and_NOT_WARN_because_documentation_is_opted_out_u() {}
    
    public func should_be_HIDDEN_and_WARN_because_no_documentation_exists_u() {}
}
